# Generated by Django 4.1.2 on 2022-10-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=500)),
                ('goalId', models.CharField(max_length=500)),
                ('firstName', models.CharField(max_length=200)),
                ('timstamp', models.CharField(max_length=500)),
                ('textField', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('employeeId', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('companyName', models.CharField(max_length=500)),
                ('managerId', models.CharField(max_length=500)),
                ('positionTitle', models.CharField(max_length=500)),
                ('startDate', models.DateField()),
                ('isManager', models.BooleanField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.CharField(max_length=500)),
                ('companyName', models.CharField(max_length=500)),
                ('goalId', models.CharField(max_length=500)),
                ('managerId', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('textField', models.TextField()),
            ],
        ),
    ]
