# Generated by Django 4.1.2 on 2022-11-01 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('commentId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=500)),
                ('goalId', models.CharField(max_length=500)),
                ('employeeId', models.CharField(max_length=500)),
                ('timstamp', models.CharField(max_length=500)),
                ('textField', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('employeeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=500)),
                ('companyName', models.CharField(max_length=500)),
                ('managerId', models.CharField(max_length=500)),
                ('positionTitle', models.CharField(max_length=500)),
                ('startDate', models.DateField()),
                ('isManager', models.BooleanField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='goal',
            fields=[
                ('employeeId', models.CharField(max_length=500)),
                ('companyName', models.CharField(max_length=500)),
                ('goalId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('managerId', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('textField', models.CharField(max_length=5000)),
            ],
        ),
    ]
