# Generated by Django 4.1.2 on 2022-10-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='textField',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='goal',
            name='textField',
            field=models.CharField(max_length=5000),
        ),
    ]
