# Generated by Django 4.1.2 on 2022-10-25 21:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pathways_app', '0002_alter_comment_textfield_alter_goal_textfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentId',
            field=models.UUIDField(default=uuid.UUID('e6a1d6ec-e973-4831-ac02-b02e06eddd97'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeId',
            field=models.UUIDField(default=uuid.UUID('8fff30a0-1e58-413b-8acb-bd62acc4c454'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goalId',
            field=models.UUIDField(default=uuid.UUID('fdb79824-7042-48f7-8a65-03d8bb0f3cb4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
