# Generated by Django 4.1.2 on 2022-10-25 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pathways_app', '0003_remove_comment_id_remove_employee_id_remove_goal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentId',
            field=models.UUIDField(default=uuid.UUID('3fc04be5-8bf7-445e-9f92-e89127ba8c89'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeId',
            field=models.UUIDField(default=uuid.UUID('c2c8e977-ffc0-45b1-932f-1b8afc722e77'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goalId',
            field=models.UUIDField(default=uuid.UUID('2e45ac7c-1691-48f8-80fd-562aad6cd451'), editable=False, primary_key=True, serialize=False),
        ),
    ]
